# ===========================================
# PRODUCTION ENVIRONMENT OVERRIDES
# ===========================================
# Only contains settings that differ from main application.yml

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:true}&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        "[format_sql]": ${JPA_FORMAT_SQL:false}
        
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

# JWT Production Settings - Shorter Expiration
jwt:
  expiration: ${JWT_EXPIRATION_MS:3600000} # 1 hour for production

# Production File Paths
app:
  upload:
    path: ${UPLOAD_PATH:/opt/figma-web-app/uploads/profiles}
  email:
    reset-token-expiry-minutes: ${EMAIL_RESET_TOKEN_EXPIRY:15} # Shorter for security

file:
  upload:
    dir: ${FILE_UPLOAD_DIR:/opt/figma-web-app/uploads/profiles/}

# Production Logging - Less Verbose
logging:
  level:
    "[com.figma.webapp]": ${LOG_LEVEL_APP:INFO}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:WARN}
    "[org.springframework.web]": ${LOG_LEVEL_WEB:WARN}
    "[org.hibernate.SQL]": ${LOG_LEVEL_SQL:ERROR}
    root: ${LOG_LEVEL_ROOT:WARN}
  file:
    name: ${LOG_FILE:/var/log/figma-app/application.log}

# Production Management - Restricted Endpoints
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_DETAILS:when-authorized}
