# ===========================================
# PRODUCTION ENVIRONMENT - COMPLETE CONFIGURATION
# ===========================================
# ALL production settings in ONE place
# Activated with: --spring.profiles.active=prod

# Server Configuration
server:
  port: ${SERVER_PORT:5001}
  servlet:
    context-path: /api

spring:
  # Production Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Production JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
        
  # Production SQL Initialization
  sql:
    init:
      mode: never
      
  # Production Security Configuration
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
      
  # Production Email Configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST}

# Production JWT Configuration - Shorter expiration for security
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour for production

# Production CORS Configuration - Specific origins only
cors:
  allowed-origins: 
    - ${FRONTEND_URL}
    - ${CORS_ORIGIN_PROD}
    - ${CORS_ORIGIN_EC2_HTTPS}
    - ${CORS_ORIGIN_S3}
    - "https://gcgcm-fe.s3.eu-north-1.amazonaws.com"
    - "https://gcgcm-fe.s3-website.eu-north-1.amazonaws.com"
    - "*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Production Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL}
  upload:
    path: /opt/figma-web-app/uploads/profiles
  email:
    reset-token-expiry-minutes: 15 # Shorter for security

# Production File Upload Configuration
file:
  upload:
    dir: /opt/figma-web-app/uploads/profiles/

# Production Logging Configuration - Minimal for performance
logging:
  level:
    "[com.figma.webapp]": INFO
    "[org.springframework.security]": WARN
    "[org.springframework.web]": WARN
    "[org.hibernate.SQL]": ERROR
    "[org.springframework.transaction]": WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/figma-app/application.log

# Production Management Configuration - Restricted
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized
