# ===========================================
# DEVELOPMENT ENVIRONMENT - COMPLETE CONFIGURATION
# ===========================================
# ALL development settings in ONE place
# Activated with: --spring.profiles.active=dev

# Server Configuration
server:
  port: 5001
  servlet:
    context-path: /api

spring:
  # Development Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/figma_app_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Development JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        
  # Development SQL Initialization
  sql:
    init:
      mode: embedded
      
  # Development Security Configuration
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
      
  # Development Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# Development JWT Configuration
jwt:
  secret: ${JWT_SECRET:dev-jwt-secret-key-for-development-only-change-in-production}
  expiration: 86400000 # 24 hours for development

# Development CORS Configuration
cors:
  allowed-origins: "*"
  allow-credentials: false

# Development Application Configuration
app:
  frontend:
    url: http://localhost:3000
  upload:
    path: uploads/profiles
  email:
    reset-token-expiry-minutes: 30

# Development File Upload Configuration
file:
  upload:
    dir: uploads/profiles/

# Development Logging Configuration
logging:
  level:
    "[com.figma.webapp]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.springframework.transaction]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/figma-app-dev.log

# Development Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
