# ===========================================
# DEVELOPMENT ENVIRONMENT CONFIGURATION
# ===========================================

server:
  port: ${SERVER_PORT:5001}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  # Development Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:figma_app_dev}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
      
  # Development Email Configuration (Console for testing)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

# JWT Configuration for Development
jwt:
  secret: ${JWT_SECRET:dev-jwt-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION_MS:86400000}

# App Configuration for Development
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  upload:
    path: ${UPLOAD_PATH:uploads/profiles}
  email:
    reset-token-expiry-minutes: ${EMAIL_RESET_TOKEN_EXPIRY:30}

# Development-specific CORS origins
cors:
  allowed-origins: 
    - ${CORS_ORIGIN_LOCALHOST_3000:http://localhost:3000}
    - ${CORS_ORIGIN_LOCALHOST_5173:http://localhost:5173}
    - ${CORS_ORIGIN_DEV:http://localhost:3001}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
  allowed-headers: "*"
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Development logging - verbose for debugging
logging:
  level:
    "[com.figma.webapp]": ${LOG_LEVEL_APP:DEBUG}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:DEBUG}
    "[org.springframework.web]": ${LOG_LEVEL_WEB:DEBUG}
    "[org.springframework.transaction]": ${LOG_LEVEL_TRANSACTION:DEBUG}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}"
  file:
    name: ${LOG_FILE:logs/figma-app-dev.log}

# Management endpoints - all enabled in development
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_DETAILS:always}

# File upload directory for development
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:uploads/profiles/}
