server:
  port: 5001
  servlet:
    context-path: /api

spring:
  main:
    allow-circular-references: true
  application:
    name: figma-web-app-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/figma_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: never
      continue-on-error: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD}
  
  # Email Configuration - AWS SES SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: liuprope@gmail.com
    password: svlhrmvrgbirwegl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.figma.webapp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/figma-app.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# File upload directory
file:
  upload:
    dir: uploads/profiles/

# App Configuration
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
  upload:
    path: ${UPLOAD_PATH:uploads/profiles}