server:
  port: ${SERVER_PORT:5001}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  main:
    allow-circular-references: true
  application:
    name: ${APP_NAME:figma-web-app-backend}
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:figma_app}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      continue-on-error: true

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}
      
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD}
  
  # Email Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS:86400000} # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: 
    - ${CORS_ORIGIN_LOCALHOST_3000:http://localhost:3000}
    - ${CORS_ORIGIN_LOCALHOST_3001:http://localhost:3001}
    - ${CORS_ORIGIN_LOCALHOST_5173:http://localhost:5173}
    - ${CORS_ORIGIN_EC2_HTTP:}
    - ${CORS_ORIGIN_EC2_HTTPS:}
    - ${CORS_ORIGIN_PROD:https://gcgcm-fe.s3.eu-north-1.amazonaws.com}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Logging Configuration
logging:
  level:
    "[com.figma.webapp]": ${LOG_LEVEL_APP:DEBUG}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:DEBUG}
    "[org.springframework.web]": ${LOG_LEVEL_WEB:DEBUG}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"
    file: "${LOG_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}"
  file:
    name: ${LOG_FILE:logs/figma-app.log}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_DETAILS:always}

# File upload directory
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:uploads/profiles/}

# App Configuration
app:
  frontend:
    url: ${FRONTEND_URL:https://gcgcm-fe.s3.eu-north-1.amazonaws.com}
  upload:
    path: ${UPLOAD_PATH:uploads/profiles}
  email:
    reset-token-expiry-minutes: ${EMAIL_RESET_TOKEN_EXPIRY:30}