# ===========================================
# FIGMA WEB APP - FRAMEWORK ESSENTIALS ONLY
# ===========================================
# This file contains ONLY Spring Boot framework configuration
# ALL environment-specific configs are in profile-specific files
# Use --spring.profiles.active=dev or --spring.profiles.active=prod

spring:
  main:
    allow-circular-references: true
  application:
    name: figma-web-app-backend
  
  # Framework-only JPA settings (no environment specifics)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    
  # Framework-only SQL settings
  sql:
    init:
      continue-on-error: true

  # Framework-only multipart settings
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cors:
  allowed-origins:
    - "*"
  allow-credentials: false
  max-age: 3600