# ===========================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# ===========================================

server:
  port: ${SERVER_PORT:5001}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  # Production Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:true}&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        "[format_sql]": ${JPA_FORMAT_SQL:false}
        
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      
  # Production Email Configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
          ssl:
            trust: ${MAIL_HOST}

# JWT Configuration for Production
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS:3600000} # 1 hour for production

# App Configuration for Production
app:
  frontend:
    url: ${FRONTEND_URL}
  upload:
    path: ${UPLOAD_PATH:/opt/figma-web-app/uploads/profiles}
  email:
    reset-token-expiry-minutes: ${EMAIL_RESET_TOKEN_EXPIRY:15}

# Production-specific CORS origins
cors:
  allowed-origins: 
    - ${FRONTEND_URL}
    - ${CORS_ORIGIN_PROD}
    - ${CORS_ORIGIN_EC2_HTTPS}
    - ${CORS_ORIGIN_S3}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Production logging - minimal for performance
logging:
  level:
    "[com.figma.webapp]": ${LOG_LEVEL_APP:INFO}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:WARN}
    "[org.springframework.web]": ${LOG_LEVEL_WEB:WARN}
    "[org.hibernate.SQL]": ${LOG_LEVEL_SQL:ERROR}
    root: ${LOG_LEVEL_ROOT:WARN}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"
    file: "${LOG_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}"
  file:
    name: ${LOG_FILE:/var/log/figma-app/application.log}

# Management endpoints - restricted in production
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_DETAILS:when-authorized}

# File upload directory for production
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:/opt/figma-web-app/uploads/profiles/}
