# ===========================================
# DEVELOPMENT ENVIRONMENT OVERRIDES
# ===========================================
# Only contains settings that differ from main application.yml

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:figma_app_dev}?createDatabaseIfNotExist=true&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:UTC}
    password: ${DB_PASSWORD:root}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        "[format_sql]": ${JPA_FORMAT_SQL:true}
        
  sql:
    init:
      mode: ${SQL_INIT_MODE:embedded}

# JWT Development Settings
jwt:
  secret: ${JWT_SECRET:dev-jwt-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION_MS:86400000} # 24 hours for development

# Development Logging - More Verbose
logging:
  level:
    "[com.figma.webapp]": ${LOG_LEVEL_APP:DEBUG}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:DEBUG}
    "[org.springframework.web]": ${LOG_LEVEL_WEB:DEBUG}
    "[org.springframework.transaction]": ${LOG_LEVEL_TRANSACTION:DEBUG}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}"
  file:
    name: ${LOG_FILE:logs/figma-app-dev.log}

# Development Management - All Endpoints Enabled
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_DETAILS:always}
